config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  resources :post_comments
  get 'users/show'
    
  devise_for :users
  resources :posts
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
    has_one_attached :image
    belongs_to :user
    has_many :post_comment, ->{ order "created_at DESC"}
end

app/models/post_comment.rb
class PostComment < ApplicationRecord  
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
        
  has_one_attached :avatar  
  has_many :posts
  validates :name, presence: true
  validates :age, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
     devise_parameter_sanitizer.permit :sign_up, keys: [:name, :age, :avatar]
     devise_parameter_sanitizer.permit :account_update, keys: [:name, :age, :avatar]
    end 
end

app/controllers/post_comments_controller.rb
class PostCommentsController < ApplicationController
  before_action :set_post_comment, only: %i[ show edit update destroy ]

  # GET /post_comments or /post_comments.json
  def index
    @post_comments = PostComment.all
  end

  # GET /post_comments/1 or /post_comments/1.json
  def show
  end

  # GET /post_comments/new
  def new
    @post_comment = PostComment.new
  end

  # GET /post_comments/1/edit
  def edit
  end

  # POST /post_comments or /post_comments.json
  def create
    @post_comment = PostComment.new(post_comment_params)
    @post_comment.user_id = current_user.id

    respond_to do |format|
      if @post_comment.save
        format.html { redirect_to @post_comment, notice: "Post comment was successfully created." }
        format.json { render :show, status: :created, location: @post_comment }
      else
        # format.html { render :new, status: :unprocessable_entity }
        url = '/posts/' + @post_comment.post_id.to_s
        format.html { redirect_to url, notice: 'Comment was posted.' }
        format.json { render json: @post_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /post_comments/1 or /post_comments/1.json
  def update
    respond_to do |format|
      if @post_comment.update(post_comment_params)
        format.html { redirect_to @post_comment, notice: "Post comment was successfully updated." }
        format.json { render :show, status: :ok, location: @post_comment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post_comment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /post_comments/1 or /post_comments/1.json
  def destroy
    @post_comment.destroy
    respond_to do |format|
      format.html { redirect_to post_comments_url, notice: "Post comment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post_comment
      @post_comment = PostComment.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_comment_params
      params.require(:post_comment).permit(:user_id, :post_id, :comment)
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: [:new, :create, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
    @post_comment = PostComment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :local, :content, :image)
    end
  
  private
    def correct_user
      post = Post.find(params[:id])    #1
      unless post.user == current_user #2
        redirect_to root_path, notice: "No access"
      end
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = current_user
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Food Story</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <header class="d-flex flex-wrap align-items-center justify-content-center justify-content-md-between py-3 mb-4 border-bottom">
      <a href="/" class="d-flex align-items-center col-md-3 mb-2 mb-md-0 text-dark text-decoration-none">
        <h4>Food Story</h4>
      </a>

      <ul class="nav col-12 col-md-auto mb-2 justify-content-center mb-md-0">
        <li><a href="/" class="nav-link px-2 link-secondary">Home</a></li>
        <li><a href="/posts" class="nav-link px-2 link-dark">Recent Posts</a></li>
        <li><a href="#" class="nav-link px-2 link-dark">About</a></li>
      </ul>

      <div class="col-md-3 text-end">
      <% if user_signed_in? %>
        <button type="button" class="btn btn-outline-primary me-22"><%= link_to current_user.name, users_show_path %></button>
        <button type="button" class="btn btn-primary"><%= link_to "ログアウト", destroy_user_session_path, method: :delete %></button>
      </div>
    </header>
  </div>  
        <% else %>
            <button type="button" class="btn btn-outline-primary me-22"><%= link_to "サインイン", new_user_session_path %></button>
            <button type="button" class="btn btn-primary"><%= link_to "ユーザ登録", new_user_registration_path %></button>
        <% end %>
      </div>
    </header>
  </div>

    <%= yield %>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.10.2/dist/umd/popper.min.js" integrity="sha384-7+zCNj/IqJ95wo16oMtfsKbZ9ccEh31eOz1HGyDuCQ6wgnyJNSYdrPa03rtR1zdB" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.min.js" integrity="sha384-QJHtvGhmr9XOIpI6YVutG+2QOK9T+ZnN4kzFN1RtK3zEFEIsxhlmWl5/YESvpZ13" crossorigin="anonymous"></script>
  </body>
</html>

app/views/post_comments/_form.html.erb
<%= form_with(model: post_comment) do |form| %>
  <% if post_comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post_comment.errors.count, "error") %> prohibited this post_comment from being saved:</h2>

      <ul>
        <% post_comment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :post_id %>
    <%= form.number_field :post_id %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_area :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/post_comments/edit.html.erb
<h1>Editing Post Comment</h1>

<%= render 'form', post_comment: @post_comment %>

<%= link_to 'Show', @post_comment %> |
<%= link_to 'Back', post_comments_path %>

app/views/post_comments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Post Comments</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Post</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @post_comments.each do |post_comment| %>
      <tr>
        <td><%= post_comment.user_id %></td>
        <td><%= post_comment.post_id %></td>
        <td><%= post_comment.comment %></td>
        <td><%= link_to 'Show', post_comment %></td>
        <td><%= link_to 'Edit', edit_post_comment_path(post_comment) %></td>
        <td><%= link_to 'Destroy', post_comment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post Comment', new_post_comment_path %>

app/views/post_comments/new.html.erb
<h1>New Post Comment</h1>

<%= render 'form', post_comment: @post_comment %>

<%= link_to 'Back', post_comments_path %>

app/views/post_comments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @post_comment.user_id %>
</p>

<p>
  <strong>Post:</strong>
  <%= @post_comment.post_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @post_comment.comment %>
</p>

<%= link_to 'Edit', edit_post_comment_path(@post_comment) %> |
<%= link_to 'Back', post_comments_path %>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :local %>
    <%= form.text_field :local %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %><br>
  </div>
  
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table class="table">
  <thead>
    <tr>
      <th>Title</th>
      <th>Local</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.local %></td>
        <td><%= link_to 'Show', post %></td>
        <% if post.user == current_user %>
            <td><%= link_to 'Edit', edit_post_path(post) %></td>
            <td><%= link_to 'Destroy', @post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Local:</strong>
  <%= @post.local %>
</p>

<p>
  <strong>Content:</strong>
  <%= @post.content %>
</p>

<p>
  <% if @post.image.attached? %>
    <%= image_tag @post.image %>
  <% end %>
</p>

<h2>Comment</h2>
<%= form_with(model: @post_comment, local: true) do |form| %>
  <div class= "field">
    <%= form.text_area :comment %>
    <%= form.hidden_field :post_id, :value => @post.id %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

<ul>
    <% @post.post_comment.each do |post_comment|%>
    <li>
    (<i><%= post_comment.user.name if post_comment.user %></i>)
    <%= post_comment.comment %></li>
        
    <% end %>
</ul>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/static_pages/home.html.erb
<main class="container">
  <div class="bg-light p-5 rounded">
    <h1>Food Story</h1>
    <p class="lead">Kết nối để chia sẻ câu chuyện du lịch ẩm thực của bạn và nhận đề xuất từ ​​những người dùng khác về các món ăn đặc sản tại một điểm đến cụ thể</p>
    <a class="btn btn-lg btn-primary" href="posts/new" role="button">Create a new post</a>
    <a class="btn btn-lg btn-primary" href="posts/" role="button">View Post</a>
  </div>
</main>

app/views/users/show.html.erb
<h1>プロフィール</h1>

<p>
  <% if @user.avatar.attached? %>
    <%= image_tag @user.avatar %>
  <% end %>
</p>

<h3>名前</h3>
<%= @user.name %>

<h3>年齢</h3>
<%= @user.age %>

<h3>メールアドレス</h3>
<%= @user.email %>

<div>
<button type="button" class="btn btn-warning"><%= link_to "Edit",edit_user_registration_path %></button>
</div>